### ISSUE TITLE
No information displayed except for location.

### ISSUE THREAD

**Issue by teacupteller** [danirabbit/nimbus#139]
![Screenshot from 2023-10-28 16 39 34](https://github.com/danirabbit/nimbus/assets/122447362/f49dac4f-f7f9-4820-ab02-fb7162a689fb)

App uses my correct location, but no information is displayed. 

Running Elementary 7.1 - Linux 6.5.7-060507-generic
-Tried Restarting
-Tried installing using both AppCenter and AppCenter (system-wide)
-Location Enabled under Privacy & Security

**Comment by danirabbit** [comment]
Hey thanks for the report! This should have been fixed in #133. I'll publish an update very soon :)
