### ISSUE TITLE
Weather information is not being displayed.

### ISSUE THREAD

**Issue by Ewertonios** [danirabbit/nimbus#140]
Weather information is not being displayed.
Location services is enabled for the app.

![image](https://github.com/danirabbit/nimbus/assets/107805966/c560dd40-ad2c-4732-80d7-34e153e53629)

![image](https://github.com/danirabbit/nimbus/assets/107805966/ccc2928b-74cc-479d-98bc-6cf8bbc0550a)

**Comment by danirabbit** [comment]
Hey thanks for the report. Should be fixed in #133. I'll publish a new release soon!

**Comment by Ewertonios** [comment]
Thank you!
