### ISSUE TITLE
Not getting weather data with Nimbus

### ISSUE THREAD

**Issue by Upsidedly** [danirabbit/nimbus#141]
I've just installed Nimbus and I see that there is no weather information visible on the application. It has access to location services yet shows nothing but 0 degrees and all other information with -.

![image](https://github.com/danirabbit/nimbus/assets/73066977/ba2beeec-85e2-4539-9a6e-404a45e86770)

**Comment by stsdc** [comment]
Same for me.

**Comment by tradecraft1** [comment]
Same issue here when I installed it through EOS AppCenter. If I build it myself it works fine.

**Comment by danirabbit** [comment]
This should be fixed in 1.1.2. Update should be available in AppCenter soon. Apologies for the delay!
