### ISSUE TITLE
Unable to Get Location

### ISSUE THREAD

**Issue by robertsanseries** [danirabbit/nimbus#24]
Does not load information on nimbus.

Command executed:
 * robertsanseries@robert-notebook:~$ com.github.danrabbit.nimbus

Erro console:
(com.github.danrabbit.nimbus:23328): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(com.github.danrabbit.nimbus:23328): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(com.github.danrabbit.nimbus:23328): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

** (com.github.danrabbit.nimbus:23328): WARNING **: MainWindow.vala:166: Failed to connect to GeoClue2 service: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.GeoClue2 was not provided by any .service files

(com.github.danrabbit.nimbus:23328): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden

![captura de tela de 2017-05-03 20-34-56](https://cloud.githubusercontent.com/assets/11967501/25704581/63e08382-30b0-11e7-8ea8-12a14c8ecceb.png)

**Comment by robertsanseries** [comment]
Just install *geoclue-2.0* and Restart Application.

* sudo apt install geoclue-2.0

**Comment by pupoxcu** [comment]
Hi Im already installed geoclue-2.0 and the result is the same. I'm in Quito, Ecuador.
![screenshot from 2017-05-20 09-40-29](https://cloud.githubusercontent.com/assets/14155322/26276645/b8b20682-3d40-11e7-887e-21b0171fe866.png)

**Comment by mariocesar** [comment]
Same problem, geoclue is installed 
```
sudo apt install geoclue-2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
geoclue-2.0 is already the newest version (2.4.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
(com.github.danrabbit.nimbus:14581): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name

(com.github.danrabbit.nimbus:14581): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name

(com.github.danrabbit.nimbus:14581): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(com.github.danrabbit.nimbus:14581): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden


(com.github.danrabbit.nimbus:14581): GWeather-WARNING **: Failed to get METAR data: 502 Proxy Error.

```

**Comment by robertsanseries** [comment]
Need to check with @danrabbit

**Comment by danirabbit** [comment]
We're using the location portal now, so location services are completely reliant on your desktop. So I'm going to close this as "fixed"
