### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by ghost** [danirabbit/nimbus#30]
Nimbus does not update its status for me; it simply displays zero degrees. When I run it from a terminal it spits out the following error: 

`(com.github.danrabbit.nimbus:3208): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden`

It does know where I am, though (approximately). I don't know whether this is a bug or simply an issue on my end.

**Comment by jkdele** [comment]
Just installed the gnome weather applet. I have the same issue there. Other locations work fine, though, so I suppose it's simply an issue with GWeather fetching some information that isn't there?

**Comment by danirabbit** [comment]
Hey thanks for your report! This was probably fixed by #133
