### ISSUE TITLE
Show widget on plank click

### ISSUE THREAD

**Issue by eliocamp** [danirabbit/nimbus#33]
When having multiple windows open there's no quick way of seeing the widget (since there's no "minimise all" in elementary OS). I think it would be cool if it jumped to the top for a couple of seconds then clicking the plank indicator.

**Comment by paoacc** [comment]
Widgets must removed from plunk forever and ever?
___
Best regards but my english is so so

**Comment by paoacc** [comment]
Because their place on tray, in Windows terms

**Comment by danirabbit** [comment]
Gonna close this since there's no more funky window management stuff since the Gtk4 port
