### ISSUE TITLE
Wrong icon after installation

### ISSUE THREAD

**Issue by inad9300** [danirabbit/nimbus#37]
![screenshot from 2017-05-18 22 13 16](https://cloud.githubusercontent.com/assets/3440331/26221556/40eb4f20-3c17-11e7-9af9-7b5621f242e7.png)

When explicitly searching for "Nimbus" is OK, though.

**Comment by bil-elmoussaoui** [comment]
You will have to refresh the icon cache.

**Comment by danirabbit** [comment]
Gonna close this since it's automatically solved in Flatpak
