### ISSUE TITLE
Shadeless borders

### ISSUE THREAD

**Issue by Tidrek** [danirabbit/nimbus#63]
Can you make the widget appear without those default shades that every window possesses? It looks more like a window and less like a widget because of that. It would be great if it looked like Desktop-Folder  from the AppCenter: https://github.com/spheras/desktopfolder

**Comment by cassidyjames** [comment]
I would guess this is out of the scope of this app… I think we'd want to have a consistent applet style for all applet-type apps if this is something we want, likely with a Granite style class constant.

**Comment by danirabbit** [comment]
I don't really want to remove the window shadow here, sorry. Closing as "design conflict"
