### ISSUE TITLE
Appear on all virtual desktops and hide from the dock

### ISSUE THREAD

**Issue by Tidrek** [danirabbit/nimbus#64]
When I switch desktops (super+left/right), I'd expect that Nimbus will also transition to them, but it stays only at the one where it was opened. Having the icon in the dock doesn't makes much sense because when another window is opened fullscreen, Nimbus doesn't gain focus and there aren't any settings exposed via right-clicking the icon. For example, Desktop-Folder doesn't appear in the dock and transitions to other desktops.

For the reference: https://github.com/spheras/desktopfolder

**Comment by janxkoci** [comment]
For me Nimbus _does_ transition between workspaces. I agree the dock icon is not very useful, but other applets do the same (such as [Monilet](https://appcenter.elementary.io/com.github.kmal-kenneth.monilet/), [Nino](https://appcenter.elementary.io/com.github.torikulhabib.nino/), and others).

**Comment by danirabbit** [comment]
You can secondary click on the window and select "Always on visible workspace" for any window, but Nimbus is unable to control its own window position in Gtk4/Wayland
