### ISSUE TITLE
"Always on top" is very erratic and doesn't work

### ISSUE THREAD

**Issue by Maccer1** [danirabbit/nimbus#87]
I've made a [video](https://streamable.com/qbf9w) to explain this erratic behaviour. 

When you right click over the top bar of nimbus it shows you an option called "always on top". Sometimes that option appears ticked and some others unticked without doing anything more than right clicking on the top bar. If you press that option is unresponsible and does what it wants.

Moreover, focusing Nimbus while other app is maximized doesn't show Nimbus at all. The maximized app appears unfocused (its window goes gray) but Nimbus doesn't appear unless I minimize all apps. 

I'm not sure what's your goal with Nimbus but if I were you I'd just use it as a desktop widget that just appears when you minimize all apps. Something like conky. And maybe also add a keyboard shortcut that shows a notification with the current weather report (for those times you want to check it quickly).

By the way, I'm using Juno and the latest Appcenter version of Nimbus as of now.

**Comment by danirabbit** [comment]
Since this issue was file Nimbus was ported to Gtk4 which drops its custom window stacking stuff, so this has been essentially fixed
